alias: 'notify on state change'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: sensor.abby_location
  - platform: state
    entity_id: sensor.becca_location
  - platform: state
    entity_id: sensor.snapshot_backup
    
action:

  - service: notify.pb
    data_template:
      message: " {{ trigger.to_state.attributes.friendly_name }} has gone from {{trigger.from_state.state}} to {{trigger.to_state.state}}. "  


