alias: 'turn furnace room light off after 5 mins'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.furnace_room_235
  to: 'off'
  for:
    minutes: 5
action:
  service: light.turn_off
  entity_id: light.furnace_room