initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.garage_door_door_sensor
  to: 'on'
  for: 
    minutes: 5
action:
  - service: notify.pb
    data:
      message: "Door to garage is ajar"
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_speaker
      message: "Excuse me.  THe door to the garage is ajar."

