alias: 'Joe leaving Leeland'
initial_state: 'on'
trigger:
  platform: state
  entity_id: sensor.joe_location
  from: 'leeland'
condition:
  condition: time
  after: '10:29:00'
action:
  - service: tts.google_say
    data:
      entity_id: media_player.kitchen_speaker
      message: "Joe has left Leeland Road Train station."
  - service: notify.ios_joesiphone7
    data:
      message: "Joe has left Leeland Rd"