alias: 'notify if house opens and noone home'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_sensor
    to: 'on'
  - platform: state
    entity_id: switch.garage_door_99
    to: 'on'
  - platform: state
    entity_id: lock.front_door_lock_4
    to: 'unlocked'
condition:
  condition: state
  entity_id: group.presence
  state: 'not_home'
action:
  service: notify.pb
  data_template:
    message: "Noone is home and {{ trigger.to_state.attributes.friendly_name }} went to {{ trigger.to_state.state }}."
