alias: 'turn off office lights when no motion'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.office_motion_161
  to: 'off'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: calendar.joe_to_work
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '05:30:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  - service: light.turn_off
    entity_id: light.office

