alias: 'turn on office lights when motion'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.office_motion_161
  to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: calendar.joe_to_work
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '23:59:59'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
  - service: light.turn_on
    entity_id: light.office
    data_template:
      brightness: >-
        {% set current_hour = now().strftime("%H") | int %}
        {%- if current_hour <= 6 %} 64
        {% elif current_hour < 20 %} 255
        {% else %} 128
        {% endif %}
  - service: switch.turn_on
    data_template:
      entity_id: >
        {% if state.sensor.temperature_sensor_1_181.state | float >= 72 %} switch.wemo_switch_charlie {% endif %}

