alias: 'lock garage and front door and shut down lights at 10pm'
initial_state: 'on'
trigger:
  platform: time
  at: '22:00:00'
action:
  - service: light.turn_off
    entity_id:
      - group.outside_lights
      - light.livingroomlamp1
      - light.livingroomlamp2
  
  - service: switch.turn_off
    entity_id: 
      - switch.garage_door_99
      - switch.bookshelf
      - switch.chinacabinet
  - service: lock.lock
    entity_id: lock.front_door_lock_4
  - service_template: " {% if is_state('input_boolean.xmas_mode', 'on') or is_state('states.switch.outside_xmas_lights_116.state', 'off') %} light.turn_off {% else %} light.turn_on {% endif %} "
    entity_id: switch.outside_xmas_lights_116  
