alias: 'openvpn down'
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.openvpn
  to: 'off'
action:
  - service: shell_command.restart_openvpn
  - delay: 00:00:30
  - service: shell_command.restart_transmission
  - service: notify.pb
    data:
      message: "openvpn restarted"
  
  