alias: "vacation mode Deus Ex Machina on Vera ock doors and close garage" 
initial_state: 'on'
trigger: 
  platform: state
  entity_id: input_boolean.vacation_mode
  to: 'on'
action:
  - service: shell_command.start_deus_ex 
  - service: lock.lock
    entity_id: lock.front_door_lock_4
  - service: switch.turn_off
    entity_id: switch.garage_door_99

